<a href="https://colab.research.google.com/github/davit3331/MachineLearning-ML-/blob/main/Copy_of_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt #for plotting shit
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values #iloc stands for locate indexes, for indeces explanation watch video
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data/handling missing data


In [ ]:
from sklearn.impute import SimpleImputer ##imported a class
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
#above I created an instance of the class to replace the missing stuff

##Now we need to apply the imputer object on the matrix of features using the fit method
'''fit method will connect the imputer to the matrix of features, or in other words, it will look at
the missing vals in the salary column and compute the avg of the salaries. Note that this wont do the
replacement, for replacement we need to use another method transform'''

imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [ ]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
'''y is depenedent variable of either test or train set, while X is the matrix of features of train or test set'''

'y is depenedent variable of either test or train set, while X is the matrix of features of train or test set'

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


Feature scaling should be done after splitting data into test and train sets to prevent data leakage, ensuring that the scaling is based solely on the training data. This prevents the model from indirectly learning information from the test set, leading to more reliable performance evaluation and better generalization to unseen data.

## Feature Scaling

**Side note:** We do not have to apply feature Scalling(Standardization) to the dummy variables(the country names - encoded by the first 3 columns which are represented as a combinations of 1s and 0s in the matrix of features).
This is because the goal of Standardization transform features to take values between -3,+3 and since 1,0 is already between that range then there is nothing
more to do for the dummy variables

Additionally, if we do apply the Standardization to the dummy variables then we will lose the interpretation behind the dummy variables in other words we will fail to determine which country corresponds to the observation. Right now for ex, we know 1 0 0 is france. After applying featuring Scalling (standardization) to this we wont know which country it is after.

**Hence we leave dummy variables alone**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#we do not apply scalling to dummy variables, so we start from 3rd column
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
'''fit mthd will only compute Mean and Std of all values, while the tansform mthod will apply the standardization formula to each value (as shown above).
This method call does both together'''

X_test[:, 3:] = sc.transform(X_test[:, 3:])
'''observe that we used the same scaller that was applied to the train set, to avoid data leakage. Additionaly,
we did not apply a fit method just transform, because the fit method was applied by the train set. We just reuse it on the test set to avoid data leakage.'''


'observe that we used the same scaller that was applied to the train set, to avoid data leakage. Additionaly,\nwe did not apply a fit method just transform, because the fit method was applied by the train set. We just reuse it on the test set to avoid data leakage.'

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
